language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
services:
  - mongodb
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
before_install:
- npm update
install:
- npm install
script:
- npm test
