language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
env:
  global:
    secure: cTMS8rtT11yzMvQK41e0z42ZtgUDzGJiMrPqy4iJfZBcpZhdsS8I5DKeJQGXUPM6HAYAfUEL1L+74DBSD3YCbMGjFB4luyccS9JI2dtqok+EIGCxpGR6ACGqLNu3moMQYHGsdvY0Xbj05jr+ljwLX/RDwrP18gU68DAoYYw9VysaZXyRKpDwtynEFBoBZbdJlpLVXSb2LvqZMzR/ln70bP/B3iZIHl8Sd56pP75/sn+D6oBsqRlof1SHTnnbxxUpeEGW0H6wSQESDf5DVR1a4HgmWfjEo08jYhgU0NT28JesQqcmlDRs3llJ9eRvCtgKxAk04bymJbQ0qMg6JdZN9ImpgHWZ/LsNI8UnpQKP1cQmIZRByihcREzzxLqAGLvmmuXj6avajLfZB1Z4pGutUBjtIp6+m62FFDYqQaHRGylvnbbFNWUvDD+YiamRiNgcVvPLjmLnhCI5XqGlpBE+bbN5DEQPhJuFYP0MHzVJHIWlS3271MtcdYXyghARFW1E6vCgbB0n/Pz4uTfZXXwMV3P5n3+ZNzrKIdWOIJ2AXMLUEvW+dwrvyTeWu8DNrAgT88xqq5QhBS57iMJpfJ/Wpi4SyBdT4TLaSzkowgGPBGJ9WtkoHIcLUUrdNk6W2A5c/jTQj77rxdyqueAAl2wXUOsf7/W0FzBB+zlTLTGKCSY=
    secure: a0AJzoTrw4BSUZAB7RmiJuUryX52lCuOEEOWgCV2fXjkrjGgiOsZlGegUm/1z8Pi0jBx2so/inyWeaKqymVBP5p0OyXCZCsLUaxb+S0KY3JpSSElt99gfoQoJXsbkuXrw8A4ke7YnLkvQSXT+B4z0em3tu95teo3U0yVFithbXh+oC+gB7ZKRgBBaja7WKvcjaQxhC+sAias71h0emUsb9WK3nwV5WkmbJgCer49tbsF1NA4H2un7jEzmJFOVKl9kcU3nWpbSQlOJ7qOqw+vE263joAAhOqyMRW7C7GHtQfLipkV8VYuJ3V7M6I50PpdWUECyvSBLcm8erLAwBMY54Ht6FonNu8SqsUSghZFd7j7Iojk2XRHPi+KTCMCZi8rJ34e787MpSYfstse6IK5fB8p0Js6hr+pvNQnt99pvmIHixO8Upm2jzhLKVEYB10Wrgddsn4rKex4PAwEnHht/QmaE9XGDtNsAqGe4qtYdEVhIwDrH1TNL/Z92mCBFoRM5JhJrNAVVHrqtezhrVIdqhtM5CESnF7WLlXrJ5r77hKDqvXrRNHEhjEdTU8nTVdZv8RjW3KBG6PdxRif1YxvvLzcYY9yzDo463jIQK4p3BjRzakqsLJtuO7rv4I4GFPrHnbeNEJ2KY9QVR+GwXMcyxUMSvn7b3P4yWCyLfpg81s=
